services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PGID: 1000
      PUID: 1000
    labels:
      docktail.service.enable: true
      docktail.service.name: "prowlarr"
      docktail.service.port: 9696
      docktail.service.network: proxy
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICE_PATH:-/opt/apps}/prowlarr/config:/config

networks:
  proxy:
    external: true
