services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      PGID: 1000
      PUID: 1000
    networks:
      - proxy
    labels:
      docktail.service.enable: true
      docktail.service.name: "radarr"
      docktail.service.port: 7878
      docktail.service.network: proxy
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOWNLOAD_PATH:-/opt/downloads}:/downloads
      - ${MEDIA_PATH:-/mnt/media}:/media
      - ${SERVICE_PATH:-/opt/apps}/radarr/config:/config

networks:
  proxy:
    external: true
