services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      PGID: 1000
      PUID: 1000
    networks:
      - proxy
    labels:
      docktail.service.enable: true
      docktail.service.name: "sonarr"
      docktail.service.port: 8989
      docktail.service.network: proxy
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOWNLOAD_PATH:-/opt/downloads}:/downloads
      - ${MEDIA_PATH:-/mnt/media}:/media
      - ${SERVICE_PATH:-/opt/apps}/sonarr/config:/config
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8989 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  proxy:
    external: true
