services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    networks:
      - proxy
    deploy:
      resources:
        limits:
          memory: 1000M
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      BASE_URL: ${BASE_URL}
    labels:
      docktail.service.enable: true
      docktail.service.name: "mealie"
      docktail.service.port: 9000
      docktail.service.network: proxy
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mealie.data:/app/data/

networks:
  proxy:
    external: true

volumes:
  mealie.data:
