services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      PGID: 1000
      PUID: 1000
      VERSION: docker
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICE_PATH}/plex/config:/config
      - ${MEDIA_PATH}:/media
