services:
  id:
    image: ghcr.io/pocket-id/pocket-id:v1.12.0
    container_name: id
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy
    labels:
      komodo.skip:
      tsbridge.enable: true
      tsbridge.service.name: "id"
      tsbridge.service.port: "1411"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/core-services/id/data:/app/data
    healthcheck:
      test: "curl -f http://localhost:1411/healthz"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

networks:
  proxy:
    external: true
