services:
  radarr4k:
    image: linuxserver/radarr:latest
    container_name: radarr4k
    restart: unless-stopped
    environment:
      PGID: 1000
      PUID: 1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOWNLOAD_PATH}:/downloads
      - ${MEDIA_PATH}:/media
      - ${SERVICE_PATH}/radarr4k/config:/config
