services:
  fetcharr:
    image: egg82/fetcharr:latest
    container_name: fetcharr
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy
    environment:
      RADARR_0_URL: ${RADARR_0_URL}
      RADARR_0_API_KEY: ${RADARR_0_API_KEY}
      SONARR_0_URL: ${SONARR_0_URL}
      SONARR_0_API_KEY: ${SONARR_0_API_KEY}
      LIDARR_0_URL: ${LIDARR_0_URL}
      LIDARR_0_API_KEY: ${LIDARR_0_API_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICE_PATH:-/opt/apps}/fetcharr/config:/app/config
      - ${SERVICE_PATH:-/opt/apps}/fetcharr/cache:/app/cache
      - ${SERVICE_PATH:-/opt/apps}/fetcharr/logs:/app/logs
      - ${SERVICE_PATH:-/opt/apps}/fetcharr/plugins:/app/plugins

networks:
  proxy:
    external: true