services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      PGID: 1000
      PUID: 1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICE_PATH}/prowlarr/config:/config
