services:
  huntarr:
    image: huntarr/huntarr:latest
    container_name: huntarr
    restart: unless-stopped
    environment:
      BASE_PATH: ${BASE_PATH}
      PGID: 1000
      PUID: 1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICE_PATH}/huntarr/config:/config
